# Generated by Django 4.2.1 on 2023-06-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='accepted_dat',
            new_name='accepted_date',
        ),
    ]
